name: "npm publish"

on:
  release:
    types:
      - published

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # List Node exeuction versions
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org/"
      - run: "npm publish triggered"
      # - run: "npm ci"
      # - run: "npm run build --if-present"
      # - run: "npm test"
      # - run: "npm publish"
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
