name: "npm publish"

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # List node versions to run tests with
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org/"
      - run: "npm ci"
      - run: "npm publish"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
